import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { SessionProvider } from "next-auth/react";
import { Providers } from "./providers";
import Navbar from "../components/navbar";
import { getServerSession } from "next-auth";
import { authOptions } from "../lib/auth";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Cinemaxx",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const session = await getServerSession(authOptions);
  
  return (
    <html lang="en">
      <body style={{ fontFamily: "Helvetica Neue, Arial, sans-serif" }}>
        
        <Providers>
          <Navbar session={session}/>
          <div style={{ paddingTop: "60px" }}>
            {children}
          </div>
        </Providers>
      </body>
    </html>
  );
}
