import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Providers } from "./providers";
import Navbar from "../components/navbar";
import { LoadingProvider } from "../contexts/LoadingContext";
import LoadingSpinner from "../components/loading";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Cinemaxx",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <LoadingProvider>
      <html lang="en">
        <body style={{ fontFamily: "Helvetica Neue, Arial, sans-serif" }}>
          <Providers>
            <Navbar />
            <div className="bg-black">
              <LoadingSpinner />
              {children}
            </div>
          </Providers>
        </body>
      </html>
    </LoadingProvider>

  );
}
